### ISSUE TITLE
why not iothub-explorer

### ISSUE THREAD

**Issue by pierreca** [robinmanuelthiel/SimpleIotHubCli#2]
Hi there - Found your package on NPM. 

Just a question out of curiosity, did you know about iothub-explorer (https://github.com/Azure/iothub-explorer) and if yes, what didn't work that pushed you to write a your own thing?

Also, if there's anything I can do to help with your project let me know. I'm the Azure IoT Node SDK maintainer, i'm always looking for new ways to help the community.

**Comment by robinmanuelthiel** [comment]
Yep, you are absolutely right. Since iothub-explorer has faced some very good improvements, there is no need for this project anymore...
